fix unauthenticated git protocol on port 9418
brimworks/lua-zlib pull request #58
Opened 2022-03-24 19:32 UTC by vadym-panchuk

The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Fix in the PR

2022-03-24 20:02 UTC, alerque requested changes

2022-03-24 20:02 UTC, alerque commented on rockspecs/lua-zlib-1.2-2.rockspec
> +   url = "git@github.com/brimworks/lua-zlib.git",
This shouldn't be an SSH reference, use this instead:

```suggestion
   url = "git+https://github.com/brimworks/lua-zlib.git",
```

2022-03-29 12:26 UTC, tkachuk commented
Hi @alerque, could you check this PR again ?
Thanks

2022-03-29 12:27 UTC, alerque approved these changes

2022-03-29 12:30 UTC, alerque commented
This change itself looks good. The next step is a matter of how the repo is maintained. Just fixing this in the rockspec doesn't get it published to LuaRocks. While it is possible to force push an updated rockspec, that will break checksums for distro packaging downstream. I think the correct way to handle this is bump the rockrel in a new file to `-3`. That probably means this file needs to be copied to the new rockspec file location and the version bumped in combination with making this change to the file. How that happens logistically is up to the maintainer.

2022-04-17 13:47 UTC, r-bk commented
@brimworks @alerque Hi! What is the status of this PR?
Currently it is impossible to install lua-zlib with luarocks.
Is there a plan to merge this PR and publish the `1.2-2` version?

2022-04-17 14:22 UTC, r-bk commented
> This change itself looks good. The next step is a matter of how the repo is maintained. Just fixing this in the rockspec doesn't get it published to LuaRocks. While it is possible to force push an updated rockspec, that will break checksums for distro packaging downstream. I think the correct way to handle this is bump the rockrel in a new file to `-3`. That probably means this file needs to be copied to the new rockspec file location and the version bumped in combination with making this change to the file. How that happens logistically is up to the maintainer.

@alerque The latest version published on https://luarocks.org/modules/brimworks/lua-zlib is `1.2-1`.
This PR crates `1.2-2`. Isn't this enough? Why `-3` is needed?

2022-04-18 02:47 UTC, merged

2022-04-18 02:50 UTC, brimworks commented
Happy Easter! Thanks for the contribution.